name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: timkrase/phpunit-coverage-badge@v1.2.0

      - name: phpunit-coverage-badge
        with:
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
